### ISSUE TITLE
Link <a> tag and css not working in iOS platform

### ISSUE THREAD

**Issue by laxman-konze** [khizar1556/html_to_pdf_plus#1]
I have run give example in iOS device from [html_to_pdf_plus](https://github.com/khizar1556/html_to_pdf_plus) repository but link not working also I have apply background color to it but not show in pdf.

Any solution for this?

**Comment by Khizar-crewLogix** [comment]
Add this to your style tag.
`<style>
    @media print {
    * {
        -webkit-print-color-adjust: exact !important;
      }
    }
</style>`

**Comment by khizar1556** [comment]
please use new version 1.0.4
