### ISSUE TITLE
support of landscape

### ISSUE THREAD

**Issue by heshaShawky** [khizar1556/html_to_pdf_plus#2]
Does this plugin support landscape A4 size, will be nice if so.

And thanks for the hardwork.

**Comment by khizar1556** [comment]
@heshaShawky support added in new version 1.0.4

**Comment by heshaShawky** [comment]
Thank you so much

**Comment by khizar1556** [comment]
> Thank you so much

Please star this repo and promote Thanks

**Comment by heshaShawky** [comment]
> > Thank you so much
> 
> Please star this repo and promote Thanks

done
